server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ry-vue-wallpaper?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      # springboot2.6集成knife4j
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#配置日志，我们所用的sql现在是不可见的，我们希望知道他是怎么执行的，所以我们必须要查看日志！
mybatis-plus:
  global-config:
    db-config:
      #      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      #      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      #      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      table-prefix: wallpaper_
  configuration-properties:
    prefix: wallpaper_ # 自定义sql中表名带前缀
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 自动驼峰命名
    map-underscore-to-camel-case: false
  mapper-locations: classpath*:/mapper/**Mapper.xml


